### ISSUE TITLE
HDR question

### ISSUE THREAD

**Issue by mrnetlex** [K1aymore/Nixos-Config#1]
It's not a issue per se, but I have seen in commit history that you got HDR running on KDE 6 with VK_HDR_LAYER. 
Should it be enough to do same you did in [this commit](https://github.com/K1aymore/Nixos-Config/commit/7b595824e9751bd219038cf13bbcfbc1a06876fe), because if I replicate this, MPV (with [proper config](https://zamundaaa.github.io/wayland/2023/12/18/update-on-hdr-and-colormanagement-in-plasma.html#fnref:3)) still wouldn't output in HDR. 
Any help would be appreciated.

**Comment by K1aymore** [comment]
Yeah, my current PC setup does have HDR support, it should work with that commit as well. My MPV config is in [packages/gui.nix](https://github.com/K1aymore/Nixos-Config/blob/master/packages%2Fgui.nix#L241).

It might not work if you don't have an AMD GPU, although I've heard you can get it working with Nvidia.

**Comment by K1aymore** [comment]
Make sure to add VK_HDR_LAYER as a package with
```
environment.systemPackages = [
  (pkgs.callPackage ./VK_hdr_layer.nix {})
];
```
rather than just adding it to your imports.

I have an RX 7600, idk what other GPUs are supported.

**Comment by mrnetlex** [comment]
I have AMD GPU too (RX 6700XT). Before official release of KDE 6, I was able to boot to Arch, install this vulkan layer from AUR and everything was working fine, so on hardware level everything is good to go. I'm generally happy with NixOS and don't want to distrohop. 
I experimented some more and find out some things, but would like to compare some things if it wasn't a problem.
1. If you run MPV with `VK_LOADER_DEBUG=error,warn,info` do `VK_HDR_LAYER` is loaded for you? (Or could you just copy what get.)
2. Does changing `SDR brightness` in KDE settings change how video looks for you in MPV?

**Comment by K1aymore** [comment]
1. If I run it with a video it does say `Inserted device layer "VK_LAYER_hdr_wsi" (/nix/store/575ynjkjsw3n4klwdymqjnrxv681s7g7-vulkan-hdr-layer-63d2eec/lib/libVkLayer_hdr_wsi.so)`, but if I run MPV without a video it just says ffmpeg info and nothing about hdr.
2. No it does not, that's how I know it's using actual HDR.

Are you using kde2nix or the actual merged plasma6 module? Both should work but you could try using my latest commit with my flake.lock idk.

**Comment by mrnetlex** [comment]
And in my case `Inserted device layer ...` is not present. At this point I have no idea why:
 - `libVkLayer_hdr_wsi.so` is in the same path in /nix/store
 - `ENABLE_HDR_WSI` is set to 1 with environment.variables
 - I use the same mpv config
 - I use plasma6 module - `services.xserver.desktopManager.plasma6.enable = true;`
 - it worked on arch
 
I think I should just assume that HDR video in linux at this point are hacks on top of the hacks and I'm just unlucky. Probably best wait for proper implementation or reinstall (maybe there are some leftovers from plasma5 and it shouldn't be too painful with nix).

**Comment by mrnetlex** [comment]
Ok, I kinda solved it, but I have no idea why does it work like that.
When I did my testing before I've always launched files through terminal. Now I tried to open a file with Dolphin for the first time and I got proper HDR. I don't know what could be different, but at least it works now.
